version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superusuario
      POSTGRES_DB: DW_Frigovel
    ports:
      - "5434:5432"
    networks:
      default:
        aliases:
          - db

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    name: dashboard
